var shotsFullGame = [
{period:1,minute:10,second:11,assist:'Kemba Walker',player:'Gerald Henderson',result:'made',distance:25,x:11,y:67},
{period:1,minute:8,second:11,assist:'Joe Johnson',player:'Deron Williams',result:'made',distance:26,x:31,y:31},
{period:1,minute:7,second:39,assist:'Mason Plumlee',player:'Deron Williams',result:'made',distance:26,x:8,y:26},
{period:1,minute:3,second:58,assist:'Andray Blatche',player:'Deron Williams',result:'made',distance:23,x:2,y:7},
{period:1,minute:3,second:31,assist:'Deron Williams',player:'Alan Anderson',result:'made',distance:25,x:7,y:24},
{period:1,minute:1,second:54,assist:'',player:'Deron Williams',result:'made',distance:26,x:6,y:24},
{period:2,minute:10,second:2,assist:'Bismack Biyombo',player:'Chris Douglas-Roberts',result:'made',distance:26,x:25,y:62},
{period:2,minute:8,second:40,assist:'Shaun Livingston',player:'Mirza Teletovic',result:'made',distance:26,x:21,y:32},
{period:2,minute:8,second:23,assist:'Chris Douglas-Roberts',player:'Luke Ridnour',result:'made',distance:25,x:13,y:66},
{period:2,minute:6,second:37,assist:'Chris Douglas-Roberts',player:'Anthony Tolliver',result:'made',distance:25,x:21,y:63},
{period:2,minute:4,second:37,assist:'Andray Blatche',player:'Mirza Teletovic',result:'made',distance:26,x:13,y:29},
{period:2,minute:1,second:8,assist:'Deron Williams',player:'Mirza Teletovic',result:'made',distance:27,x:31,y:32},
{period:3,minute:7,second:26,assist:'Paul Pierce',player:'Joe Johnson',result:'made',distance:26,x:38,y:28},
{period:3,minute:6,second:58,assist:'Josh Mcroberts',player:'Kemba Walker',result:'made',distance:28,x:36,y:62},
{period:3,minute:3,second:10,assist:'Andray Blatche',player:'Mirza Teletovic',result:'made',distance:26,x:21,y:32},
{period:3,minute:1,second:8,assist:'Jorge Gutierrez',player:'Joe Johnson',result:'made',distance:23,x:48,y:7},
{period:4,minute:10,second:38,assist:'Deron Williams',player:'Mirza Teletovic',result:'made',distance:26,x:38,y:28},
{period:4,minute:9,second:56,assist:'Kemba Walker',player:'Chris Douglas-Roberts',result:'made',distance:24,x:49,y:85},
{period:4,minute:6,second:13,assist:'Deron Williams',player:'Mirza Teletovic',result:'made',distance:25,x:18,y:30},
{period:4,minute:5,second:3,assist:'Andray Blatche',player:'Deron Williams',result:'made',distance:26,x:24,y:32},
{period:4,minute:3,second:8,assist:'Josh Mcroberts',player:'Kemba Walker',result:'made',distance:28,x:39,y:64},
{period:4,minute:2,second:47,assist:'Mason Plumlee',player:'Joe Johnson',result:'made',distance:25,x:33,y:30},
{period:5,minute:3,second:44,assist:'Deron Williams',player:'Paul Pierce',result:'made',distance:25,x:32,y:30},
{period:5,minute:2,second:35,assist:'Kemba Walker',player:'Chris Douglas-Roberts',result:'made',distance:23,x:48,y:87},
{period:5,minute:2,second:15,assist:'Shaun Livingston',player:'Joe Johnson',result:'made',distance:25,x:2,y:17},
{period:1,minute:1,second:7,assist:'',player:'Alan Anderson',result:'made',distance:1,x:24,y:6},
{period:2,minute:11,second:3,assist:'',player:'Chris Douglas-Roberts',result:'made',distance:1,x:26,y:88},
{period:2,minute:9,second:14,assist:'',player:'Shaun Livingston',result:'made',distance:2,x:27,y:6},
{period:2,minute:7,second:52,assist:'',player:'Chris Douglas-Roberts',result:'made',distance:1,x:25,y:87},
{period:3,minute:11,second:2,assist:'',player:'Josh Mcroberts',result:'made',distance:1,x:26,y:87},
{period:3,minute:9,second:25,assist:'',player:'Michael Kidd-Gilchrist',result:'made',distance:1,x:25,y:87},
{period:4,minute:9,second:32,assist:'',player:'Alan Anderson',result:'made',distance:2,x:23,y:6},
{period:4,minute:0,second:59,assist:'Shaun Livingston',player:'Deron Williams',result:'made',distance:1,x:24,y:7},
{period:1,minute:9,second:0,assist:'Gerald Henderson',player:'Al Jefferson',result:'made',distance:1,x:25,y:87},
{period:2,minute:4,second:20,assist:'Kemba Walker',player:'Josh Mcroberts',result:'made',distance:1,x:26,y:88},
{period:3,minute:8,second:3,assist:'Shaun Livingston',player:'Mason Plumlee',result:'made',distance:1,x:25,y:7},
{period:1,minute:11,second:37,assist:'Paul Pierce',player:'Shaun Livingston',result:'made',distance:10,x:21,y:15},
{period:1,minute:10,second:25,assist:'',player:'Deron Williams',result:'made',distance:17,x:32,y:22},
{period:1,minute:9,second:53,assist:'',player:'Joe Johnson',result:'made',distance:10,x:31,y:14},
{period:1,minute:8,second:30,assist:'Gerald Henderson',player:'Michael Kidd-Gilchrist',result:'made',distance:19,x:39,y:75},
{period:1,minute:4,second:46,assist:'Kemba Walker',player:'Al Jefferson',result:'made',distance:18,x:39,y:77},
{period:1,minute:4,second:16,assist:'',player:'Kemba Walker',result:'made',distance:16,x:11,y:81},
{period:2,minute:7,second:9,assist:'',player:'Luke Ridnour',result:'made',distance:16,x:10,y:84},
{period:2,minute:6,second:54,assist:'',player:'Shaun Livingston',result:'made',distance:16,x:22,y:22},
{period:2,minute:3,second:30,assist:'Joe Johnson',player:'Paul Pierce',result:'made',distance:11,x:18,y:14},
{period:2,minute:3,second:15,assist:'Kemba Walker',player:'Al Jefferson',result:'made',distance:8,x:24,y:80},
{period:2,minute:1,second:30,assist:'Kemba Walker',player:'Al Jefferson',result:'made',distance:17,x:18,y:72},
{period:3,minute:10,second:47,assist:'',player:'Joe Johnson',result:'made',distance:15,x:28,y:21},
{period:3,minute:1,second:43,assist:'Joe Johnson',player:'Jorge Gutierrez',result:'made',distance:18,x:37,y:19},
{period:4,minute:10,second:57,assist:'Luke Ridnour',player:'Cody Zeller',result:'made',distance:19,x:8,y:79},
{period:4,minute:8,second:52,assist:'deron williams',player:'andray blatche',result:'made',distance:7,x:25,y:13},
{period:4,minute:8,second:15,assist:'Jorge Gutierrez',player:'Deron Williams',result:'made',distance:19,x:37,y:21},
{period:4,minute:7,second:58,assist:'',player:'Luke Ridnour',result:'made',distance:19,x:44,y:84},
{period:4,minute:7,second:18,assist:'Deron Williams',player:'Jorge Gutierrez',result:'made',distance:19,x:14,y:21},
{period:4,minute:2,second:29,assist:'Kemba Walker',player:'Al Jefferson',result:'made',distance:17,x:12,y:77},
{period:4,minute:0,second:26,assist:'Shaun Livingston',player:'Deron Williams',result:'made',distance:21,x:44,y:15},
{period:5,minute:0,second:10,assist:'',player:'Chris Douglas-Roberts',result:'made',distance:21,x:4,y:84},
{period:1,minute:8,second:47,assist:'Paul Pierce',player:'Deron Williams',result:'made',distance:2,x:23,y:6},
{period:1,minute:5,second:13,assist:'Kemba Walker',player:'Al Jefferson',result:'made',distance:1,x:24,y:87},
{period:1,minute:3,second:10,assist:'Gerald Henderson',player:'Al Jefferson',result:'made',distance:1,x:25,y:87},
{period:2,minute:11,second:33,assist:'Luke Ridnour',player:'Josh Mcroberts',result:'made',distance:1,x:24,y:87},
{period:3,minute:6,second:35,assist:'',player:'Kemba Walker',result:'made',distance:2,x:27,y:88},
{period:3,minute:4,second:13,assist:'Andray Blatche',player:'Jorge Gutierrez',result:'made',distance:1,x:26,y:6},
{period:3,minute:0,second:55,assist:'Kemba Walker',player:'Al Jefferson',result:'made',distance:1,x:24,y:88},
{period:4,minute:7,second:31,assist:'Kemba Walker',player:'Cody Zeller',result:'made',distance:1,x:24,y:88},
{period:4,minute:1,second:38,assist:'Shaun Livingston',player:'Mason Plumlee',result:'made',distance:1,x:24,y:6},
{period:5,minute:4,second:7,assist:'Josh Mcroberts',player:'Al Jefferson',result:'made',distance:0,x:25,y:88},
{period:1,minute:6,second:52,assist:'',player:'Al Jefferson',result:'made',distance:1,x:26,y:88},
{period:1,minute:5,second:50,assist:'Josh Mcroberts',player:'Gerald Henderson',result:'made',distance:2,x:27,y:88},
{period:1,minute:5,second:33,assist:'',player:'Deron Williams',result:'made',distance:7,x:23,y:13},
{period:2,minute:8,second:6,assist:'Shaun Livingston',player:'Andray Blatche',result:'made',distance:1,x:24,y:6},
{period:2,minute:3,second:43,assist:'',player:'Kemba Walker',result:'made',distance:15,x:35,y:77},
{period:2,minute:2,second:58,assist:'',player:'Paul Pierce',result:'made',distance:10,x:19,y:14},
{period:2,minute:2,second:36,assist:'Gerald Henderson',player:'Al Jefferson',result:'made',distance:10,x:35,y:85},
{period:2,minute:1,second:49,assist:'',player:'Al Jefferson',result:'made',distance:6,x:19,y:86},
{period:3,minute:9,second:56,assist:'',player:'Gerald Henderson',result:'made',distance:16,x:9,y:87},
{period:3,minute:6,second:3,assist:'Kemba Walker',player:'Al Jefferson',result:'made',distance:14,x:13,y:81},
{period:3,minute:5,second:5,assist:'',player:'Al Jefferson',result:'made',distance:13,x:13,y:82},
{period:3,minute:2,second:44,assist:'Gerald Henderson',player:'Kemba Walker',result:'made',distance:12,x:24,y:76},
{period:3,minute:2,second:10,assist:'',player:'Joe Johnson',result:'made',distance:9,x:16,y:7},
{period:3,minute:1,second:55,assist:'',player:'Al Jefferson',result:'made',distance:1,x:26,y:88},
{period:4,minute:9,second:15,assist:'',player:'Luke Ridnour',result:'made',distance:18,x:7,y:85},
{period:4,minute:6,second:33,assist:'',player:'Josh Mcroberts',result:'made',distance:2,x:24,y:86},
{period:4,minute:0,second:36,assist:'',player:'Kemba Walker',result:'made',distance:17,x:40,y:80},
{period:5,minute:3,second:23,assist:'Al Jefferson',player:'Josh Mcroberts',result:'made',distance:1,x:25,y:87},
{period:5,minute:0,second:43,assist:'',player:'Kemba Walker',result:'made',distance:19,x:16,y:71},






























{period:1,minute:6,assist:'',player:'Deron Williams',result:'missed',distance:25,x:18,y:30},
{period:1,minute:4,assist:'',player:'Joe Johnson',result:'missed',distance:25,x:6,y:23},
{period:1,minute:1,assist:'',player:'Deron Williams',result:'missed',distance:23,x:48,y:10},
{period:1,minute:0,assist:'',player:'Gerald Henderson',result:'missed',distance:31,x:14,y:59},
{period:2,minute:9,assist:'',player:'Anthony Tolliver',result:'missed',distance:23,x:48,y:84},
{period:2,minute:8,assist:'',player:'Chris Douglas-Roberts',result:'missed',distance:26,x:10,y:67},
{period:2,minute:5,assist:'',player:'Mirza Teletovic',result:'missed',distance:26,x:34,y:30},
{period:2,minute:2,assist:'',player:'Mirza Teletovic',result:'missed',distance:25,x:32,y:30},
{period:2,minute:0,assist:'',player:'Mirza Teletovic',result:'missed',distance:56,x:33,y:61},
{period:3,minute:10,assist:'',player:'Deron Williams',result:'missed',distance:28,x:18,y:33},
{period:3,minute:8,assist:'',player:'Deron Williams',result:'missed',distance:25,x:29,y:31},
{period:3,minute:3,assist:'',player:'Kemba Walker',result:'missed',distance:23,x:2,y:84},
{period:3,minute:2,assist:'',player:'Mirza Teletovic',result:'missed',distance:25,x:23,y:31},
{period:4,minute:10,assist:'',player:'Alan Anderson',result:'missed',distance:25,x:15,y:29},
{period:4,minute:5,assist:'',player:'Kemba Walker',result:'missed',distance:23,x:48,y:86},
{period:4,minute:4,assist:'',player:'Deron Williams',result:'missed',distance:25,x:18,y:30},
{period:4,minute:3,assist:'',player:'Luke Ridnour',result:'missed',distance:27,x:44,y:69},
{period:1,minute:11,assist:'',player:'Michael Kidd-Gilchrist',result:'missed',distance:3,x:28,y:88},
{period:4,minute:7,assist:'',player:'Andray Blatche',result:'missed',distance:2,x:23,y:6},
{period:1,minute:10,assist:'',player:'Gerald Henderson',result:'missed',distance:20,x:28,y:68},
{period:1,minute:6,assist:'',player:'Al Jefferson',result:'missed',distance:14,x:11,y:85},
{period:1,minute:3,assist:'',player:'Michael Kidd-Gilchrist',result:'missed',distance:17,x:25,y:71},
{period:1,minute:2,assist:'',player:'Joe Johnson',result:'missed',distance:6,x:25,y:12},
{period:1,minute:0,assist:'',player:'Alan Anderson',result:'missed',distance:26,x:4,y:21},
{period:1,minute:0,assist:'',player:'Al Jefferson',result:'missed',distance:16,x:11,y:80},
{period:2,minute:8,assist:'',player:'Anthony Tolliver',result:'missed',distance:26,x:35,y:64},
{period:2,minute:7,assist:'',player:'Alan Anderson',result:'missed',distance:10,x:15,y:8},
{period:2,minute:6,assist:'',player:'Chris Douglas-Roberts',result:'missed',distance:6,x:25,y:82},
{period:2,minute:5,assist:'',player:'Kemba Walker',result:'missed',distance:18,x:19,y:71},
{period:2,minute:5,assist:'',player:'Kemba Walker',result:'missed',distance:19,x:10,y:77},
{period:2,minute:3,assist:'',player:'Andray Blatche',result:'missed',distance:13,x:31,y:18},
{period:2,minute:1,assist:'',player:'Deron Williams',result:'missed',distance:26,x:28,y:32},
{period:2,minute:0,assist:'',player:'Al Jefferson',result:'missed',distance:18,x:11,y:77},
{period:2,minute:0,assist:'',player:'Paul Pierce',result:'missed',distance:26,x:20,y:32},
{period:2,minute:0,assist:'',player:'Kemba Walker',result:'missed',distance:15,x:24,y:73},
{period:3,minute:11,assist:'',player:'Shaun Livingston',result:'missed',distance:9,x:16,y:9},
{period:3,minute:10,assist:'',player:'Al Jefferson',result:'missed',distance:9,x:24,y:79},
{period:3,minute:9,assist:'',player:'Joe Johnson',result:'missed',distance:6,x:28,y:11},
{period:3,minute:9,assist:'',player:'Shaun Livingston',result:'missed',distance:9,x:29,y:14},
{period:3,minute:7,assist:'',player:'Gerald Henderson',result:'missed',distance:15,x:11,y:82},
{period:3,minute:6,assist:'',player:'Paul Pierce',result:'missed',distance:26,x:35,y:30},
{period:3,minute:5,assist:'',player:'Paul Pierce',result:'missed',distance:11,x:27,y:17},
{period:3,minute:5,assist:'',player:'Kemba Walker',result:'missed',distance:26,x:45,y:71},
{period:3,minute:4,assist:'',player:'Andray Blatche',result:'missed',distance:17,x:34,y:21},
{period:3,minute:4,assist:'',player:'Gerald Henderson',result:'missed',distance:17,x:18,y:72},
{period:3,minute:1,assist:'',player:'Al Jefferson',result:'missed',distance:15,x:11,y:83},
{period:3,minute:1,assist:'',player:'Gerald Henderson',result:'missed',distance:16,x:40,y:84},
{period:3,minute:0,assist:'',player:'Kemba Walker',result:'missed',distance:19,x:24,y:69},
{period:3,minute:0,assist:'',player:'Mirza Teletovic',result:'missed',distance:26,x:4,y:21},
{period:4,minute:11,assist:'',player:'Chris Douglas-Roberts',result:'missed',distance:27,x:16,y:63},
{period:4,minute:10,assist:'',player:'Kemba Walker',result:'missed',distance:10,x:35,y:85},
{period:4,minute:7,assist:'',player:'Kemba Walker',result:'missed',distance:26,x:16,y:64},
{period:4,minute:6,assist:'',player:'Kemba Walker',result:'missed',distance:9,x:25,y:79},
{period:4,minute:5,assist:'',player:'Deron Williams',result:'missed',distance:6,x:26,y:12},
{period:4,minute:5,assist:'',player:'Chris Douglas-Roberts',result:'missed',distance:26,x:39,y:66},
{period:4,minute:3,assist:'',player:'Mirza Teletovic',result:'missed',distance:25,x:46,y:20},
{period:4,minute:1,assist:'',player:'Al Jefferson',result:'missed',distance:10,x:18,y:81},
{period:4,minute:1,assist:'',player:'Chris Douglas-Roberts',result:'missed',distance:26,x:43,y:69},
{period:5,minute:4,assist:'',player:'Deron Williams',result:'missed',distance:21,x:14,y:24},
{period:5,minute:1,assist:'',player:'Chris Douglas-Roberts',result:'missed',distance:27,x:43,y:68},
{period:5,minute:1,assist:'',player:'Joe Johnson',result:'missed',distance:26,x:47,y:19},
{period:5,minute:1,assist:'',player:'Al Jefferson',result:'missed',distance:17,x:25,y:71},
{period:5,minute:1,assist:'',player:'Deron Williams',result:'missed',distance:15,x:13,y:15},
{period:5,minute:0,assist:'',player:'Joe Johnson',result:'missed',distance:26,x:27,y:32},
{period:1,minute:6,assist:'',player:'Al Jefferson',result:'missed',distance:2,x:25,y:86},
{period:1,minute:6,assist:'',player:'Michael Kidd-Gilchrist',result:'missed',distance:1,x:26,y:88},
{period:1,minute:4,assist:'',player:'Andray Blatche',result:'missed',distance:2,x:25,y:8},
{period:1,minute:2,assist:'',player:'Andray Blatche',result:'missed',distance:2,x:27,y:7},
{period:1,minute:1,assist:'',player:'Cody Zeller',result:'missed',distance:2,x:27,y:88},
{period:2,minute:11,assist:'',player:'Alan Anderson',result:'missed',distance:2,x:23,y:7},
{period:2,minute:7,assist:'',player:'Chris Douglas-Roberts',result:'missed',distance:2,x:27,y:88},
{period:4,minute:6,assist:'',player:'Deron Williams',result:'missed',distance:1,x:24,y:7},
{period:4,minute:6,assist:'',player:'Kemba Walker',result:'missed',distance:1,x:24,y:87},
{period:4,minute:4,assist:'',player:'Al Jefferson',result:'missed',distance:2,x:23,y:87},
{period:4,minute:4,assist:'',player:'Al Jefferson',result:'missed',distance:2,x:27,y:87},
{period:4,minute:4,assist:'',player:'Kemba Walker',result:'missed',distance:1,x:25,y:87},
{period:4,minute:2,assist:'',player:'Mason Plumlee',result:'missed',distance:1,x:24,y:6},
{period:5,minute:0,assist:'',player:'Paul Pierce',result:'missed',distance:26,x:20,y:32},
{period:1,minute:9,assist:'',player:'Joe Johnson',result:'missed',distance:13,x:35,y:14},
{period:3,minute:11,assist:'',player:'Al Jefferson',result:'missed',distance:14,x:14,y:79},
{period:3,minute:0,assist:'',player:'Joe Johnson',result:'missed',distance:15,x:12,y:13},
{period:5,minute:2,assist:'',player:'Joe Johnson',result:'missed',distance:14,x:39,y:9},
{period:4,minute:2,assist:'',player:'Joe Johnson',result:'missed',distance:8,x:19,y:12},
{period:1,minute:9,assist:'',player:'Al Jefferson',result:'missed',distance:3,x:27,y:86},
{period:2,minute:7,assist:'',player:'Chris Douglas-Roberts',result:'missed',distance:3,x:25,y:85},
{period:3,minute:3,assist:'',player:'Alan Anderson',result:'missed',distance:23,x:2,y:8},
{period:3,minute:1,assist:'',player:'Kemba Walker',result:'missed',distance:2,x:23,y:88},
{period:5,minute:0,assist:'',player:'Josh McRoberts',result:'missed',distance:3,x:25,y:85},
{period:5,minute:0,assist:'',player:'Shaun Livingston',result:'missed',distance:1,x:24,y:6}
];